### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by Trufi** [2gis/2gl#1]
- [x] orthographic camera
- [x] camera up vector
- [x] camera lookAt method
- [x] ~~frustum~~
- [x] ray intersect plane method
- [x] renderer options: antialias
- [x] renderer methods: setPixelRatio, setClearColor
- [x] sprite
- [x] another program for markers
- [x] ~~add setters and getters for class fields~~
- [x] ~~add options to texture~~
- [x] mesh opacity
- [x] geometries concat

**Comment by Trufi** [comment]
- [ ] object opacity don't work correctly
- [ ] make more simple mesh without colors and lights

**Comment by Trufi** [comment]
- [ ] add performance tests

**Comment by Trufi** [comment]
Use
```
gl.enable( gl.BLEND );
gl.blendEquationSeparate( gl.FUNC_ADD, gl.FUNC_ADD );
gl.blendFuncSeparate( gl.SRC_ALPHA, gl.ONE_MINUS_SRC_ALPHA, gl.ONE, gl.ONE_MINUS_SRC_ALPHA );
```
for sprites

**Comment by Trufi** [comment]
- [ ] add texture options

**Comment by Trufi** [comment]
- [ ] rename .childs to .children

**Comment by Trufi** [comment]
- [ ] add diffuse colors
